services:
  pyroboadvisor:
    image: ghcr.io/xaviv/pyroboadvisor-arm-docker:latest
    ports:
      - "6800:6800"
    environment:
      - IbLoginId=
      - IbPassword=
      - TradingMode=live
      - AcceptNonBrokerageAccountWarning=yes
      - ReadOnlyApi=no
      - BypassOrderPrecautions=yes
      - fecha_inicio=2019-01-01
      - money=100000
      - numberStocksInPortfolio=10
      - orderMarginBuy=0.005
      - orderMarginSell=0.005
      - apalancamiento=1.6
      - ring_size=252
      - rlog_size=22
      - cabeza=5
      - seeds=1000
      - percentil=90
      - prediccion=1
      - key=
      - email=
      - modo=3
      - hora=10:00
      - puerto=4001
      - enable_novnc=1
      - har=1
      - hretorno=1
      - hrandom=1
      - multiploMantenimiento=6
      - b=true
      - eodhd_key=
      - polygon_key=

